# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "portfolio-theme"
license = "MIT"
description = "A boilerplate starter theme using Tailwind CSS."
homepage = "A theme for my portfolio"

[author]
  name = "Diego Sánchez"
  homepage = "https://github.com/diegosanchezp"
