baseURL = "http://example.org/"
languageCode = "en-us"
title = "Diego Sánchez portfolio"
theme = "portfolio-theme"

[module]

  [[module.mounts]]
    source = "./themes/portfolio-theme/node_modules/vanilla-ripplejs/ripple.min.js"
    target = "static/ripple.min.js"

